`build-index`: Make `_get_block` perfectly general and precise
Use PCRE2 regular expressions to detect all and only YAML keys and
thereby detect all and only YAML blocks with great precision. However,
this slows down build-index considerably (because each call of
_get_block requires multiple invocations of pcre2grep), so, as beautiful
as it is, this functionality should be abandoned. For the purposes of
build-index, it will suffice to ensure that 'title:' and 'keyword:' are
contained within the header; it is not necessary to detect other keys

diff --git a/.local/bin/build-index b/.local/bin/build-index
--- a/.local/bin/build-index
+++ b/.local/bin/build-index
@@ -1,132 +1,140 @@
 #!/bin/zsh
 
-# {{{1 Utility functions for `_get_block()`
+# Utility functions for _get_block {{{1
 
-__get_lines() {
-    # Takes an array of line numbers as its argument. Eliminate all line
-    # numbers prior to the possible beginning of a YAML block. It's possible
-    # for a `...` line to appear in the document before the YAML block does.
-    # So, if the first parameter is the line number of a `...` line, remove
-    # that parameter from the array. Repeat until the first parameter is the
-    # line number of a `---` line. If the `---` line is followed by a blank
-    # line, it cannot be initiating a valid YAML block, so remove its line
-    # number from the array. Finally, if the `---` is not the first line of the
-    # document and is not preceded by a blank line, it cannot be initiating a
-    # valid YAML block, so remove its line number from the array.
-    while [[
-        ! $file[$1] == ---[[:space:]]# ||
-        $file[$1+1] == [[:space:]]# ||
-        (! $1 -eq 1 && ! $file[$1-1] == [[:space:]]#)
-    ]]; do
+__start_found() { # {{{2
+    # Return 1 if the start of a YAML block is found; return 0 if it is not
+    # found. Takes the array `start_end_line_numbers` as its argument
+    local -i possible_start
+    local -i possible_end
+    while true; do
+        # The start must be a `---` line (as opposed to a `...` line); it must
+        # not be followed by a blank line; and, if it is not the first line of
+        # the document, it must be preceded by a blank line. Eliminate any
+        # lines that do not meet these criteria until a possible start is
+        # found.
+        while [[
+            $file[$1] != ---[[:space:]]# ||
+            $file[$1+1] == [[:space:]]# ||
+            ($1 -ne 1 && $file[$1-1] != [[:space:]]#)
+        ]]; do
+            shift
+
+            if (( $# < 2 )); then
+                start_end_line_numbers=( $* )
+                return 1
+            fi
+        done
+
+        start_end_line_numbers=( $* )
+        local -i possible_start=$start_end_line_numbers[1]
+        local -i possible_end=$start_end_line_numbers[2]
+
+        # Check if block is empty
+        (( possible_end - possible_start == 1 )) && return 0
+
+        # Check if there is a key
+        if [[ -n $key_line_numbers ]] && __key_found $key_line_numbers; then
+            start_end_line_numbers=( $* )
+            return 0
+        else
+            shift
+            continue
+        fi
+    done
+}
+
+__key_found() { # {{{2
+    # Return 0 if a key is found in the possible YAML block; return 1 if one is
+    # not found. Takes `key_line_numbers` as its argument
+    while (( $1 < possible_start )); do
         shift
-        # If there are less than two parameters left, then there is no valid
-        # YAML block in this document
-        if (( $# < 2 )); then
+
+        if (( $# == 0 )); then
+            key_line_numbers=( $* )
             return 1
         fi
     done
 
-    print -l $*
-}
-
-__check_lines() {
-    # Takes an array of line numbers as its argument. Determine whether or not
-    # line `$1` really is the beginning of a YAML block. If line `$2` is a
-    # `...` line, then the lines between line `$1` and line `$2` will be
-    # treated as a YAML block by Pandoc. Otherwise, the lines will only be
-    # treated as a YAML block by Pandoc if the line after line `$1` contains a
-    # key. If neither of these conditions is met, remove the first parameter
-    # from the array.
-    if  [[
-        ! $file[$2] == ...[[:space:]]# &&
-        ! $file[$1+1] == [[:space:]]#[^-]##:*
-    ]]; then
-        shift
-        print -l $*
-        return 1
-    else
-        print -l $*
+    if (( $1 > possible_start && $1 < possible_end )); then
+        key_line_numbers=( $* )
         return 0
+    else
+        key_line_numbers=( $* )
+        return 1
     fi
 }
+# }}}2
 
-# {{{1 _get_block()
+# _get_block() {{{1
+
+setopt rc_quotes
+
+declare key_start_chars='[^\-?:,[\]{}#&*!|>''"%@`[:space:]]'
+declare key_can_start_if_chars='[?:\-](?=[^[:space:]])'
+declare key_subsequent_chars='(\S#|:\S|[^[:space:]:#])*'
+declare key_chars="(${key_start_chars}|${key_can_start_if_chars})\
+${key_subsequent_chars}"
+declare key_regex='^\s*'${key_chars}'(\s+'${key_chars}')*\s*:(\s|$)'
+declare quoted_key_regex='^\s*''([^'']|'''')*''\s*:(\s|$)'
+declare dquoted_key_regex='^\s*"([^"]|\\")*(?<!\\)"\s*:(\s|$)'
 
 _get_block() {
-    # Store contents of file in array; this will make is easier to get lines by
-    # line number
-    local -a file=( "${(@f)$(cat $1)}" )
-
-    # Scan the document for all lines that might validly open or close a YAML
-    # block, and store line numbers in an array
-    local -a line_numbers=(
-        ${(f)"$(rg --line-number '^(---|\.\.\.)\s*$' $1 | cut -d : -f 1)"}
+    local -a start_end_line_numbers=(
+        ${(f)"$(
+            pcre2grep --line-number '^(---|\.\.\.)\s*$' $1 | cut -d : -f 1
+        )"}
     )
 
-    if (( $#line_numbers < 2 )); then
+    if (( $#start_end_line_numbers < 2 )); then
         echo 'build-index: cannot get YAML block for' $1 >&2
         return 1
     fi
 
-    local -i m=$line_numbers[1]
-    local -i n=$line_numbers[2]
+    local -a key_line_numbers=(
+        ${(f)"$(
+            pcre2grep --line-number $key_regex $1 | cut -d : -f 1
+        )"}
+    )
+    key_line_numbers+=(
+        ${(f)"$(
+            pcre2grep --line-number $quoted_key_regex $1 | cut -d : -f 1
+        )"}
+    )
+    key_line_numbers+=(
+        ${(f)"$(
+            pcre2grep --line-number $dquoted_key_regex $1 | cut -d : -f 1
+        )"}
+    )
+    key_line_numbers=( ${(n)key_line_numbers} )
+
+    local -a file=( "${(@f)$(cat $1)}" )
+    local -i block_start
+    local -i block_end
     local -a block=()
 
-    while (( $#line_numbers > 0 )); do
-        # Pass `line_numbers` to `__get_lines`
-        if ! line_numbers=( ${(f)"$(__get_lines $line_numbers)"} ); then
-            # Only throw an error if a YAML block wasn't found on previous
-            # iterations of the loop
-            if (( $#block == 0 )); then
-                echo 'build-index: cannot get YAML block for' $1 >&2
-                return 1
-            fi
+    while __start_found $start_end_line_numbers; do
+        block_start=$start_end_line_numbers[1]
+        block_end=$start_end_line_numbers[2]
+        if (( block_end - block_start == 1 )); then
+            [[ ! -n $got_empty_block ]] && local -i got_empty_block=1
+        else
+            block+=( $file[block_start+1,block_end-1] )
         fi
 
-        while (( $#line_numbers > 1 )); do
-            # Pass `line_numbers` to `__check_lines`. If `check_lines` returns
-            # `0`, then the first number in `line_numbers` really is the number
-            # of a line that initiates a YAML block
-            if line_numbers=( ${(f)"$(__check_lines $line_numbers)"} ); then
-                break
-            else
-                # If `__check_lines` returns `1`, that could mean two things.
-                # Either we've filtered `line_numbers` down to less than two
-                # elements, in which case there must not be a valid YAML block,
-                # or the first number in `line_numbers` is not really the
-                # number of a line that initiates a YAML block, in which case
-                # we need to pass `line_numbers` back to `__get_lines` to
-                # filter `line_numbers` again until we have another possible
-                # line number (if there is one) for a line initiating a YAML
-                # block. Then, at the beginning of the next iteration of the
-                # `while` loop, we pass `line_numbers` to `__check_lines`
-                # again. We repeat this until there are less than two elements
-                # left in `line_numbers` or we've found the number of a line
-                # that initiates a YAML block.
-                if (( $#line_numbers < 2 )); then
-                    if (( $#block == 0 )); then
-                        echo 'build-index: cannot get YAML block for' $1 >&2
-                        return 1
-                    fi
-                else
-                    line_numbers=( ${(f)"$(__get_lines $line_numbers)"} )
-                fi
-            fi
-        done
-
-        if (( $#line_numbers < 2 )); then
-            line_numbers=( $line_numbers[2,-1] )
+        # Remove the starting and ending line numbers from the array
+        start_end_line_numbers=( $start_end_line_numbers[3,-1] )
+        if [[ ! -n $start_end_line_numbers ]]; then
             break
         fi
-
-        m=$line_numbers[1] # Line number of the start of the YAML block
-        n=$line_numbers[2] # Line number of the end of the YAML block
-        block+=( $file[m+1,n-1] )
-
-        line_numbers=( $line_numbers[3,-1] )
     done
 
-    # Cache `block` in an associative array
+    if [[ ! -n $block && ! -n $got_empty_block ]]; then
+        echo 'build-index: cannot get YAML block for' $1 >&2
+        return 1
+    fi
+
+    # Cache the block(s) in the `blocks` associative array
     blocks[$1]=${(j:++:)block}
 }
 
