Rewrite `untar` with several improvements
1.  Add check that arguments were supplied
2.  Use loop so that multiple arguments can be handled
3.  Add option to trash original files

diff --git a/.local/share/zsh/functions/untar b/.local/share/zsh/functions/untar
--- a/.local/share/zsh/functions/untar
+++ b/.local/share/zsh/functions/untar
@@ -1,6 +1,22 @@
 # Extract a `tar` file into a directory of the same name in the parent
 # directory
 
-file=${*:?Tarball must be specified.}
-mkdir ${file%.tar*}
-tar -xf $file -C ${file%.tar*}
+# Before proceeding, check that arguments were passed
+if [[ ! $* ]]; then
+    echo 'Error: argument required' >&2
+    return 1
+fi
+
+# Check for option
+if [[ $1 == '--trash' || $1 == '-t' ]]; then
+    topt=1
+    shift
+fi
+
+for file in $*; do
+    mkdir ${file%.tar*}
+    tar -xf $file --cd ${file%.tar*}
+done
+
+# If option was passed, trash files
+(( topt == 1 )) && trash $*
